version: '3.8'

networks:
  dev:
    driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: next
    ports:
      - '3000:3000'
    networks:
      - dev
    volumes:
      - /Users/fernandobraghiroli/getrich/getrich-frontend:/next