// Seems like _app.tsx
import '../styles/globals.scss'
import type { Metadata } from 'next'
import { inter } from '../styles/fonts'

export const metadata: Metadata = {
  title: 'Getrich',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
